[[constraint]]
  name = "github.com/bitrise-io/go-utils"
  branch = "master"

[[constraint]]
  name = "github.com/bitrise-tools/go-android"
  branch = "master"

[[constraint]]
  name = "github.com/bitrise-tools/go-steputils"
  branch = "master"

[[constraint]]
  name = "github.com/bitrise-tools/go-xcode"
  branch = "master"
